# Site settings
title:       cto.coffee
email:       benjamin@squeakyvessel.com
author:      Benjamin Reitzammer
description: "cto.coffee - Let's talk about people & tech. The podcast for people who care about people."
baseurl:     "/"
url:         "https://cto.coffee"

show_related_posts: false
show_post_footers:  false

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
sass:
  compressed: true
